name: Package openrtm-aist-python
on:
  repository_dispatch:
    types:
    - package-master
  push:
    branches:
    - master
jobs:
  package:
    uses: jrl-umi3218/github-actions/.github/workflows/package-project.yml@master
    with:
      main-branch: master
      update-stable-and-head: true
      deps: '["gergondet/openhrp3"]'
    secrets:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
